# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='userpass',
            new_name='user_pass',
        ),
    ]
