# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0002_auto_20160315_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_regdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 10, 1, 54, 982596)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_status',
            field=models.IntegerField(default=1),
        ),
    ]
