# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0003_auto_20160315_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_regdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 10, 24, 39, 320359)),
        ),
    ]
